### ISSUE TITLE
Use of parenthesis instead of %29 and %28

### ISSUE THREAD

**Issue by philippe44** [libwww-perl/URI#72]
I've seen that canonical() replaces URI with %28 and %29 by "(" and ")". I'm not sure that RFC 3986 is really against that, but I think it says that it can be replaced, but don't have to and might be problematic in certain case. I had that issue with one site

**Comment by genio** [comment]
As an example:

```
$ perl -MURI -E 'say URI->new(q<https://foo.com/foo%28bar>)->canonical->as_string;'
https://foo.com/foo(bar
```

The comparable same code in Mojo::URL would be:

```
$ perl -MMojo::URL -E 'say Mojo::URL->new(q<https://foo.com/foo%28bar>)->to_abs->to_string'
https://foo.com/foo%28bar
```

\* Explicitness sprinkled about to make things obvious

**Comment by shadowcat-mst** [comment]
Since either behaviour is RFC compliant, could you please be more specific about the problem you've encountered?

I agree that the RFC says CAN so there's no specific reason to do either, but after URI behaved the way it did for this long there's probably also code out there relying on the current behaviour - so if you want to propose that URI.pm changes, you need to both give a real actual example of where the problem is, and then we need to try and work out whether the change would fix more things than it breaks.

**Comment by philippe44** [comment]
This url https://content.production.cdn.art19.com/validation=1594591337,90b3859f-c305-59db-a2b7-69ad41cdacc7,CimnocG29n73pIZ6k9s1BwQl8L8/episodes/fb60ee48-a284-4c79-b6e2-4232d73f1f7e/bad7e795b3b30839cfe5427a4b0fbbc6a97433e807744712f79551105c70676b867f75c24130ae689ba6a35dabd99942a0ba0bac7e6e498695b6c7e9818ff0bb/Bada%20Australie%20%281%29.mp3, if you make it canonical and then try to GET it, it will fail (sorry, it's a french podcast :-))

I absolutely understand your reluctance to make such change, I'm not sure myself what is the right thing to do

**Comment by vanHoesel** [comment]
`canonical` from `URI` is definitely doing the right thing for `http`.

You asked the URI object to return a normalised version of it. Since parenthesis are not part of any http sub-delimiters and therefore not even included in a component of the URI that then requires percentage-escaping for included values, it is suggested to unescape those (and anything else not part of the 'required' reserved characters).

[RFC7230 2.7.3.  http and https URI Normalization and Comparison](https://tools.ietf.org/html/rfc7230#section-2.7.3)
> Characters other than those in the "reserved" set are equivalent to their percent-encoded octets: the normal form is to not encode them (see Sections 2.1 and 2.2 of [RFC3986]).

[RFC3986 2.2 Reserved Characters](https://tools.ietf.org/html/rfc3986#section-2.2)
>If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be percent-encoded before the URI is formed.

Many of the component exist of `1* pchar` where `char` is defined as `unreserved` / `pct-encoded` / `sub-delims` / `:` / "@"`

And as mentioned at my explanation beginnings `sub-delims`  = `!` / `$` / `&` / `'` / `(` / `)` / `*` / `+` / `,` / `;` / `=`.

You could have avoided the problem by just using the original components being used `as_string`, then it would not be de-encoded and just be `%28`.

The difficulty is indeed that percentage-escaping and de-encoding for normalisation are scheme dependent, some may indeed use parenthesis as pert of the component delimiters.

**Comment by philippe44** [comment]
Understood, thank you. 

So with that, I think the initial code had an issue as it was doing ->canonical->as_string and should then do ->as_string only

**Comment by vanHoesel** [comment]
honestly, I think it is an issue with the server dealing with the receiving request, `http://...../Bada Australie (1).mp3` should just accept percentage encode as well as non encoded URL's, those `(` and `)` are not delimiters in an URI for http schemes and therefore are not required to be encoded.

**Comment by vanHoesel** [comment]
@genio , I doubt that `Mojo::URL` method `to_abs` and the `URI` method `canonical` are actually doing the same thing or  having the same purpose.

**Comment by genio** [comment]
@vanHoesel It uses Mojo::Path to canonicalize the path part of the URL https://metacpan.org/release/Mojolicious/source/lib/Mojo/URL.pm#L138-147
https://metacpan.org/source/SRI/Mojolicious-8.56/lib/Mojo/Path.pm#L9-17

**Comment by vanHoesel** [comment]
@genio , I was only looking at the documentation, not at the code. And I did say I doubt they were doing the same.

Now having looked at the code bits you showed and into the massive library of supported schemes for URI, it most defiantly should be different. And as a prove:

```
> perl -MMojo::URL -E'say Mojo::URL->new("http://example.com:80/foo/bar.txt")->to_abs'
http://example.com:80/foo/bar.txt
```
vs
```
> perl -MURI -E'say URI->new("http://example.com:80/foo/baz.txt")->canonical'
http://example.com/foo/baz.txt
```

Which I expected reading a bit of the code and `URI` being explicit on how they try to canonicalise a URI

**Comment by genio** [comment]
@vanHoesel Right you are. I was only intending to show the difference in the path part of the canonicalization. But, as you say, Mojo's implementation is quite a bit different from that of URI's. I wasn't intending to argue that they're meant entirely equivalently; apologies for any confusion added.

**Comment by vanHoesel** [comment]
@genio at no point have I felt you wanted to argue about anything, neither did I have any intention to make a point or anything like that. When I said, "doubt" it meant I did not investigate, and would like to trust documentation, without having to look any further and figure out what code is doing. However, when brought up, it is always an interesting exercise for the curious programmer to see what is happening and learn and understand.
