### ISSUE TITLE
Scheme/Protocol relative URLs are not parsed properly

### ISSUE THREAD

**Issue by kelson42** [libwww-perl/URI#75]
Test:
```
$ cat test.pl 
#!/usr/bin/perl

use URI;

my $u = URI->new("//www.perl.com");
print $u->host."\n";
```

I get:
```
Can't locate object method "host" via package "URI::_generic" at ./test.pl line 6.
```

I expect:
```
www.perl.com
```

**Comment by vanHoesel** [comment]
Hi Kelson,

I think you mistakenly take URI as 'the thing' to address a resource one the internet and thus requires port 80, and things have a 'http' scheme by default.

Since you didn't specify a `scheme` you ended up with a `URI::_generic` object, not a `URI::http` and this didn't have a `host` method.

See the manuals: [URI Server Methods](https://metacpan.org/pod/URI#SERVER-METHODS).

Hope this helps, or otherwise explain why URI should had given you the expected result.

**Comment by kelson42** [comment]
@vanHoesel Thank you for the explanation
