### ISSUE TITLE
Some modules in the distribution have inconsistent $VERSION

### ISSUE THREAD

**Issue by neilb** [libwww-perl/URI#76]
Most modules in the distribution have the same version number as the dist itself. As I write this, that's 1.76.

And then we have:

* `URI::WithBase` 2.20
* `URI::Escape` 3.31
* `URI::file` 4.21
* `URI::URL` 5.04
* `URI::Heuristic` 4.20

Maybe bump the distribution version number to 6.00 and bring them all inline?

I realise that it's _allowed_ to have different version numbers on packages compared to the dist,
but it has the potential to confuse.

**Comment by oalders** [comment]
Thanks @neilb, I remember we discussed this at some point. I dug back into the logs and it looks like the consensus was to bump to `5.05`.

> 5.05 at least doesn't have the optics of "we *just* made a major release so you should pay attention"

**Comment by neilb** [comment]
Good point -- 5.05 is a better choice.

**Comment by vanHoesel** [comment]
I think that even a bump from 1.76 to 5.05 looks like a major update, URI itself is at 1.76. So, if it is about the disguise of the version number, then what about 'v6.1.1', that has a minor update version

**Comment by neilb** [comment]
Wearing my PAUSE admin hat, I always recommend against changing version numbering scheme for an established distribution, particularly a switch *to* semantic versioning. Plenty of people have been bitten by this over the last few years, most recently someone who was understandably surprised that going from 0.1 to 0.2.1 was a "down versioning step" (0.2.1 maps to decimal version 0.002001, which is less than 0.1).

Bumping the major, you'd get away with it, but still, I'd strongly recommend sticking with the existing scheme.

**Comment by vanHoesel** [comment]
6.01 ?

**Comment by karenetheridge** [comment]
The above discussion is why I lean towards doing nothing.  The versions have been misaligned for 20+ years already with no harm. Why change now?

**Comment by petdance** [comment]
I'm not seeing any problem with having the different modules having different versions.

I think it makes more sense to only bump up the version of a given module if it's been updated.  If all I care about is URI::URL, then bumping its number because the URI package bumps up its number is misleading.  I'll think that URI::URL has an update I need to be aware of, but indeed it has not.

**Comment by neilb** [comment]
Let's say a distribution has modules Foo::Bar and Foo::Bar::Utilities. Foo::Bar uses things in the latter module, and in a release the file Foo::Bar::Utilities has changes that change the behaviour of Foo::Bar, but there are no changes to lib/Foo/Bar.pm. You'd have to remember to bump the version of Foo::Bar as well as Foo::Bar::Utilities.

If they're all part of distribution Foo, then it's safest to bump all the versions at the same time, so you're saying "this is the version of Foo::Bar that shipped with Foo 1.23". Otherwise you've got to be very sure that your version number changes are "truthful".

I raised this because I got confused by the difference. Sure, it only wasted a minute or two of my time, until I worked out what was going on, but my assumption is that it might trip other people up as well.

**Comment by vanHoesel** [comment]
on the one hand, I totally agree on not bumping up any version at all.

on the other hand, it is super silly to have files with their own version numbers within the same distribution.

I am of the opinion that all files should be versioned the same way, and when updating just update all the files... that makes it consistent.

Also, mention the version in the POD under `=head1 VERSION`

We can do that

@neilb 👍

**Comment by petdance** [comment]
> it is super silly to have files with their own version numbers within the same distribution.

What's silly about it, other than it's not how you'd do it?

**Comment by vanHoesel** [comment]
@petdance , if 'silly' is not the appropriate word for it, then at least it is confusing, and thus dangerous.

Try to be honest with yourself and have a look at URI::file on MetaCPAN, where do you look for the version number... right, if it wasn't for this discusion, you would have said "at the top: **Olaf Alders / URI 1.76 / URI::file**"

So, if people easily make that mistake, it will end up wrong into `cpanfile` where it very likely would say `require 'URI::file' => '=1.76'`.

Other than that, I can not find any reference in the Change Log for a 'URI::file version 4.21' Only 'Release' info.

**Comment by oalders** [comment]
My thoughts.

1) I find the current state of affairs confusing. The only reason I initially found out about it was because someone had opened a ticket saying they were having issues upgrading the module and I had to do a bit of digging. It wasn't the end of the world, but it's time a couple of us could have spent on other things. Like walking through a dewy meadow, or holding a puppy.

2) It's not a hard problem to solve. The version bump may raise some eyebrows, but that's what the Changelog is for. It's one more surprising thing now, rather than bumping up against this occasionally and having to remember why we have the current state of affairs.

**Comment by oalders** [comment]
Found the issue. #73 is what caused the initial discussion.

**Comment by petdance** [comment]
Sure, it can be confusing, and I also think it's confusing to see a version bump for a module that has not been changed.  I think both points of view have been stated and established.

There are valid concerns on both sides.  So how can we address both of these potential sources of confusion?

I'll suggest that maybe the changelog for the package should address changes at the module level, so that in my example where I only care about URI::URL, I can easily see that it hasn't changed in the previous 3-4 updates.

**Comment by oalders** [comment]
I don't have an issue with the changelog dealing with changes at the module level. That makes sense. It's also not too hard to diff the module between versions if you need that kind of granularity. https://metacpan.org/diff/file?target=OALDERS/URI-1.76/lib%2FURI.pm&source=ETHER%2FURI-1.73%2Flib%2FURI.pm

**Comment by petdance** [comment]
> It's also not too hard to diff the module 

Sure, the user can diff the module, and the point of the changelog is to make it so the user doesn't need to.

**Comment by oalders** [comment]
Right, different workflows. At my `$work`, we'd generally check the Changelog and then likely diff the whole dist before upgrading. We upgrade all Perl modules weekly, so the diffs are generally not that big.

**Comment by oalders** [comment]
Closed via #77

**Comment by petdance** [comment]
> We upgrade all Perl modules weekly, 

We upgrade when we have a reason to, which is why the changelog is key for us.

**Comment by simbabque** [comment]
This has actually affected me a few days ago as well. My team building a Debian package for Twitter::API, and somewhere down in the dependencies there's URI::Escape. But the liburi-perl that Debian has gets confused with the module version vs the dist version when you use dpkg to install dependencies. We ended up patching the META.json file in WWW::OAuth to make the URI::Escape version much lower so it would accept Debian stretch's liburi-perl.
